on:
  push:
    branches:
      - "*"

name: check

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run csr tests
        run: cargo test --no-default-features --features hydrate --lib
      - name: Run ssr tests
        run: cargo test --no-default-features --features ssr

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Linting csr
        run: cargo clippy --no-default-features --lib --features hydrate -- -D warnings
      - name: Linting ssr
        run: cargo clippy --no-default-features --features ssr -- -D warnings

  helm:
    name: Helm Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint ./helm-chart
